name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.1'
      - name: Run tests
        run: |
          go test ./...
      # Linter step removed due to compatibility issues in CI environment.
      # You can re-enable golangci-lint in CI once the action binary is compatible
      # with the project's Go toolchain version.
